### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gabrielbsx** [efipay/sdk-node-apis-efi#1]
Ao utilizar o pixCreateCharge os os atributos corretos, não está enviando nenhuma requisição para a api da EFI.
Ao dar um catch do error o mesmo está undefined!

![image](https://github.com/efipay/sdk-node-apis-efi/assets/19240300/2ec1d64a-4f25-483b-9c7b-f088c4d563cf)

-   SO: Windows 11 e Arch Linux
-   Versão do Node 18.18
-   Versão da SDK 1.1.2 e 1.1.0

**Comment by joao-muniz-efi** [comment]
Ola, @gabrielbsx. Espero que esteja bem.
Sugerimos que atualize para a versão mais recente do pacote e caso a falha persista abra uma outra issue referente à nova versão.
