### ISSUE TITLE
Type para envio Pix esá errado

### ISSUE THREAD

**Issue by ChristoPy** [efipay/sdk-node-apis-efi#4]
**Descreva o bug**
A documentação diz que o retorno das chamadas a rota **PUT /v2/gn/pix/:idEnvio** retornam:
```json
{
  "idEnvio": "12453567890123456789",
  "e2eId": "E09089356202011251226APIff82f2e5",
  "valor": "12.31",
  "horario": {
    "solicitacao": "2021-11-25T12:26:42.905Z"
  },
  "status":"EM_PROCESSAMENTO"
}
```

Porém a tipagem do método `pixSend` diz que os types de retorno são os mesmos que o método recebe:
```md
(method) PixMethods.pixSend(params: {
    idEnvio: string;
}, body: {
    valor: string;
    pagador: {
        chave: string;
        infoPagador?: string;
    };
    favorecido: {
        chave?: string;
        contaBanco?: {
            nome: string;
            cpf?: string;
            cnpj?: string;
            codigoBanco: string;
            agencia: string;
            conta: string;
            tipoConta: string;
        };
        cpf?: string;
        cnpj?: string;
    };
}): Promise<{
    valor: string;
    pagador: {
        chave: string;
        infoPagador?: string;
    };
    favorecido: {
        chave?: string;
        contaBanco?: {
            nome: string;
            cpf?: string;
            cnpj?: string;
            codigoBanco: string;
            agencia: string;
            conta: string;
            tipoConta: string;
        };
        cpf?: string;
        cnpj?: string;
    };
}>
PUT /v2/gn/pix/:idEnvio

Realiza o envio de Pix.

Para capturar uma falha utilize o catch, os campos disponíveis no objeto serão nome e mensagem.

@param params

@param body
```
**Como Reproduzir**
Basta acessar a instancia de `EfiPay` e no método `sendPix` a tipagem deve aparecer.

No print abaixo podemos ver que a tipagem não é a mesma da API

**Comportamento esperado**
A tipagem deveria seguir ao que a API retorna, tanto para casos de sucesso, quanto para casos de erro.

**Capturas de tela**
<img width="1033" alt="Screenshot 2024-09-29 at 16 56 07" src="https://github.com/user-attachments/assets/19a83a00-151d-4857-9b06-774eb3d9d394">

**Desktop (preencha as seguintes informações):**

-   SO: macOS Sonoma
-   Versão do Node: 22.2.0
-   Versão da SDK [por exemplo 1.0.0]: 1.2.6

**Comment by joao-muniz-efi** [comment]
Oi @ChristoPy. Espero que esteja bem.
Informamos que o retorno do método pixSend foi corrigido na [Realese 1.2.7](https://github.com/efipay/sdk-node-apis-efi/releases/tag/1.2.7).
Agradecemos por relatar a situação. 😊
